openapi: 3.0.0
info:
  version: 1.0.0
  title: defol-app-backend
  description: Especificación del backend de DEFOL

x-amazon-apigateway-request-validators:
  body:
    validateRequestParameters: false
    validateRequestBody: true
  params:
    validateRequestParameters: true
    validateRequestBody: false
  all:
    validateRequestParameters: true
    validateRequestBody: true

paths:
  /preguntas:
    get:
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PreguntasGet.Arn}/invocations
        httpMethod: POST
        type: aws
        requestTemplates:
          application/json: |
            {
              "usrId": $context.authorizer.principalId
            }
        responses:
          default:
            statusCode: 200
          ".*PREGUNTAS_GET_ERROR.*":
            statusCode: 500
      summary: obtiene el listado de preguntas
      tags:
        - pregunta
      responses:
        200:
          description: listado de preguntas
  /dashboard/resumen-preguntas:
    get:
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ResumenPreguntasGet.Arn}/invocations
        httpMethod: POST
        type: aws
        requestTemplates:
          application/json: |
            {
              "usrId": $context.authorizer.principalId
            }
        responses:
          default:
            statusCode: 200
          ".*RESUMEN_PREGUNTAS_GET_ERROR.*":
            statusCode: 500
      summary: obtiene la cantidad de preguntas realizadas, pendientes y replicas realizadas por un usuario
      tags:
        - pregunta
      responses:
        200:
          $ref: "#/components/responses/200ResumenPreguntas"
  /convenios:
    get:
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ConveniosGet.Arn}/invocations
        httpMethod: POST
        type: aws
        requestTemplates:
          application/json: |
            {
              "usrId": $context.authorizer.principalId
            }
        responses:
          default:
            statusCode: 200
          ".*CONVENIOS_GET_ERROR.*":
            statusCode: 500
      summary: obtiene el listado de convenios
      tags:
        - convenio
      responses:
        200:
          $ref: "#/components/responses/200ConvenioList"
        500:
          description: error al obtener convenios desde dynamo

components:
  schemas:
    Convenio:
      title: Convenio
      description: información de un convenio
      type: object
      properties:
        cod:
          type: string
        nombre:
          type: string
      example:
        cod: "CMX1"
        nombre: "Convenio Marco"
    ResumenPreguntas:
      title: ResumenPreguntas
      description: cantidad de preguntas por cada estado
      type: object
      properties:
        totalPreguntasPendientes:
          type: number
        totalPreguntasRealizadas:
          type: number
        totalReplicasPendientes:
          type: number
      example:
        totalPreguntasPendientes: 10
        totalPreguntasRealizadas: 20
        totalReplicasPendientes: 2
  responses:
    200ConvenioList:
      description: Listado de convenios
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Convenio"
    200ResumenPreguntas:
      description: Cantidad de preguntas por cada estado
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ResumenPreguntas"