AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Description: Backend del administrador del portal de clientes de defol

Parameters:
  Branch:
    Type: String
    Description: nombre de la rama
  ResourcesBucket:
    Type: String
    Description: bucket que aloja los recursos
  Sha:
    Type: String
    Description: identificador de la ejecución del CICD
  ConvenioTable:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de tabla Convenio
  ConvenioModeradorTable:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de tabla Convenio-Moderador
  ConvenioContactoTable:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de tabla Convenio-Contacto
  PreguntaTable:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de tabla Pregunta
  CategoriaTable:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de tabla Categoria
  EmailIndex:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de indice de tabla Pregunta
  EstadoIndex:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de indice de tabla Pregunta
  PreguntaEstadoIndex:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de indice de tabla Pregunta
  EjecutivoEmailEstadoIndex:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de indice de tabla Pregunta
  FechaActualizacionIndex:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de indice de tabla Pregunta
  ConvenioCodIndex:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de indice de tabla ConvenioModerador
  ContactoEmailIndex:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de indice de tabla ConvenioContacto
  UserConvenioIndex:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de indice de tabla Pregunta
  DynamoTokensBucket:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre de bucket para almacenar tokens de APIs
  UserPoolArn:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Arn del user pool de cognito
  SignalEventBus:
    Type: AWS::SSM::Parameter::Value<AWS::String>
    Description: Nombre del Bus de Servicios de Signal

Globals:
  Function:
    Runtime: nodejs12.x
    Timeout: 200
    MemorySize: 1024
    Layers:
      - !Ref RuntimeDependenciesLayer
    Environment:
      Variables:
        CONVENIO_TABLE: !Ref ConvenioTable
        CONVENIO_MODERADOR_TABLE: !Ref ConvenioModeradorTable
        CONVENIO_CONTACTO_TABLE: !Ref ConvenioContactoTable
        PREGUNTA_TABLE: !Ref PreguntaTable
        CATEGORIA_TABLE: !Ref CategoriaTable
        PREGUNTA_EMAIL_INDEX: !Ref EmailIndex
        PREGUNTA_ESTADO_INDEX: !Ref PreguntaEstadoIndex
        PREGUNTA_FECHA_ACTUALIZACION_INDEX: !Ref FechaActualizacionIndex
        ESTADO_INDEX: !Ref EstadoIndex
        EJECUTIVO_EMAIL_ESTADO_INDEX: !Ref EjecutivoEmailEstadoIndex
        CONVENIO_COD_INDEX: !Ref ConvenioCodIndex
        CONTACTO_EMAIL_INDEX: !Ref ContactoEmailIndex
        USER_CONVENIO_INDEX: !Ref UserConvenioIndex
        DYNAMO_TOKENS_BUCKET: !Ref DynamoTokensBucket
        SIGNAL_BUS_NAME: !Ref SignalEventBus

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: WriteCloudWatchLogs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        - PolicyName: QueryDynamoDB
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                  - s3:*
                  - events:PutEvents
                Resource: "*"

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      Name: !Sub ${AWS::StackName}-api
      DefinitionBody:
        "Fn::Transform":
          Name: AWS::Include
          Parameters:
            Location: !Sub s3://${ResourcesBucket}/${AWS::StackName}/${Sha}/openapi.yaml
      Auth:
        Authorizers:
          CUPAuthorizer:
            UserPoolArn: !Ref UserPoolArn
            Type: COGNITO_USER_POOLS

  PreguntasGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/preguntas
      Handler: preguntas.get
      Role: !GetAtt LambdaRole.Arn
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /preguntas
            Method: get

  PreguntaDetailGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/preguntas
      Handler: preguntas.detail
      Role: !GetAtt LambdaRole.Arn
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /pregunta
            Method: get

  ReplicaPut:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/preguntas
      Handler: preguntas.put
      Role: !GetAtt LambdaRole.Arn
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /pregunta
            Method: put

  ConveniosGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/convenios
      Handler: convenios.get
      Role: !GetAtt LambdaRole.Arn
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /convenios
            Method: get

  ConvenioDetalleGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/convenios
      Handler: convenios.detail
      Role: !GetAtt LambdaRole.Arn
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /convenio
            Method: get

  ConveniosPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/convenios
      Handler: convenios.post
      Role: !GetAtt LambdaRole.Arn
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /convenios
            Method: post

  ContactosPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/contactos
      Handler: contactos.post
      Role: !GetAtt LambdaRole.Arn
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /contactos
            Method: post

  ContactosMaxPreguntasPut:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/contactos
      Handler: contactos.maxPreguntasPut
      Role: !GetAtt LambdaRole.Arn
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /contacto
            Method: put

  ModeradoresPost:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/src/moderadores
      Handler: moderadores.post
      Role: !GetAtt LambdaRole.Arn
      Events:
        Get:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /moderadores
            Method: post

  RuntimeDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Runtime dependencies for Lambdas
      ContentUri: ./dist/layer
      CompatibleRuntimes:
        - nodejs12.x
      RetentionPolicy: Retain

  ApiGatewayDomainNameParamater:
    Type: AWS::SSM::Parameter
    Properties:
      Description: API Gateway domain name paramater
      Name: !Sub /defol/${Branch}/admin/backend/api-gateway-domain-name
      Type: String
      Value: !Sub ${Api}.execute-api.${AWS::Region}.amazonaws.com
