## Action Secrets:
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - AWS_REGION

name: build-backend

on:
  push:
    branches:
      - master
      - stage
      - develop

jobs:
  params:
    runs-on: ubuntu-latest
    outputs:
      libs: ${{ steps.packages-libs-changed.outputs.any_changed }}
      backend: ${{ steps.packages-backend-changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: packages-libs-changed
        name: detect changes on packages/libs
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: |
            .github/workflows/all.yml
            packages/libs
      - id: packages-backend-changed
        name: detect changes on packages/backend
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: |
            .github/workflows/all.yml
            packages/backend
      - id: extract-branch
        name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"


  publish-libs:
    runs-on: ubuntu-latest
    needs: params
    if: needs.params.outputs.libs == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - name: npm-install
        working-directory: ./packages/libs
        run: npm install --production
      - name: npm-publish
        working-directory: ./packages/libs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish

  build-deploy:
    runs-on: ubuntu-latest
    needs: [params, publish-libs]
    if: needs.params.outputs.libs == 'true' || needs.params.outputs.backend == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - uses: aws-actions/setup-sam@v1
      - name: installing typescript
        run: npm install -g typescript
      - name: npm-install-production
        working-directory: ./packages/backend
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install --production
      - name: lambda-layer
        working-directory: ./packages/backend
        run: |
          mkdir -p dist/layer/nodejs
          cp -r node_modules/ dist/layer/nodejs/
      - name: npm-install
        working-directory: ./packages/backend
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install
      - name: npm-run-build
        working-directory: ./packages/backend
        run: npm run-script build
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: upload-openapi
        uses: zdurham/s3-upload-github-action@master
        env:
          S3_BUCKET: ${{ format('defol-{0}-resources', needs.params.outputs.branch }} defol-${GITHUB_REF##*/}-resources
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FILE: ./packages/backend/openapi.yaml
          S3_KEY: ${{ format('defol-{0}-backend/{1}', needs.params.outputs.branch, github.sha }}
      - name: sam-package
        working-directory: ./packages/backend
        run: sam package --s3-bucket defol-${GITHUB_REF##*/}-resources --output-template-file packaged.yaml --template-file cloudformation.yaml
      - name: sam-deploy
        working-directory: ./packages/backend
        run: |
          sam deploy --template-file packaged.yaml --no-confirm-changeset --no-fail-on-empty-changeset \
          --stack-name defol-${GITHUB_REF##*/}-backend --s3-bucket defol-${GITHUB_REF##*/}-resources \
          --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }} \
          --parameter-overrides Env=${GITHUB_REF##*/} Sha=${github.sha}
