## Action Secrets:
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - AWS_REGION

name: build-backend

on:
  push:
    branches:
      - master
      - stage
      - develop

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      libs: ${{ steps.packages-libs-changed.outputs.any_changed }}
      backend: ${{ steps.packages-backend-changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: packages-libs-changed
        name: detect changes on packages/libs
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: |
            .github/workflows/all.yml
            packages/libs
      - id: packages-backend-changed
        name: detect changes on packages/backend
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: |
            .github/workflows/all.yml
            packages/backend

  publish-libs:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.libs == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - name: npm-install
        working-directory: ./packages/libs
        run: npm install --production
      - name: npm-publish
        working-directory: ./packages/libs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish

  build-deploy:
    runs-on: ubuntu-latest
    needs: [changes, publish-libs]
    if: needs.changes.outputs.libs == 'true' || needs.changes.outputs.backend == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - uses: aws-actions/setup-sam@v1
      - name: installing typescript
        run: npm install -g typescript
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: npm-install
        working-directory: ./packages/backend
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install --production
      - name: lambda-layer
        working-directory: ./packages/backend
        run: |
          mkdir -p dist/layer/nodejs
          cp -r node_modules/ dist/layer/nodejs/
      - name: sam-package
        working-directory: ./packages/backend
        run: sam package
      - name: sam-deploy
        working-directory: ./packages/backend
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name defol-${GITHUB_REF##*/}-backend --s3-bucket defol-${GITHUB_REF##*/}-resources --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }}
