## Action Secrets:
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - AWS_REGION

name: build-backend

on:
  push:
    branches:
      - master
      - stage
      - develop

jobs:
  params:
    runs-on: ubuntu-latest
    outputs:
      update-libs: ${{ steps.commit-message-libs.outputs.textFound }}
      libs: ${{ steps.packages-libs-changed.outputs.any_changed }}
      backend: ${{ steps.packages-backend-changed.outputs.any_changed }}
      frontend: ${{ steps.packages-frontend-changed.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: commit-message-libs
        uses: dlouisenz/last-commit-message-text-finder-action@v1.5
        with:
          textToFind: "@libs-update"
      - id: packages-libs-changed
        name: detect changes on packages/libs
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: |
            packages/libs
      - id: packages-backend-changed
        name: detect changes on packages/backend
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: |
            .github/workflows/all.yml
            packages/backend
      - id: packages-frontend-changed
        name: detect changes on packages/frontend
        uses: tj-actions/changed-files@v1.1.3
        with:
          files: |
            .github/workflows/all.yml
            packages/frontend

  publish-libs:
    runs-on: ubuntu-latest
    needs: params
    if: needs.params.outputs.update-libs == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - name: npm-install
        working-directory: ./packages/libs
        run: npm install --production
      - name: npm-publish
        working-directory: ./packages/libs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish
  publish-root:
    runs-on: ubuntu-latest
    needs: params
    if: needs.params.outputs.update-libs == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - name: npm-install
        working-directory: ./packages/root
        run: npm install --production
      - name: npm-publish
        working-directory: ./packages/root
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish

  backend:
    runs-on: ubuntu-latest
    needs: [params, publish-libs]
    if: always() && (needs.params.outputs.update-libs == 'true' || needs.params.outputs.backend == 'true')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - uses: aws-actions/setup-sam@v1
      - name: installing typescript
        run: npm install -g typescript
      - name: npm-install-production
        working-directory: ./packages/backend
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install --production
      - name: lambda-layer
        working-directory: ./packages/backend
        run: |
          mkdir -p dist/layer/nodejs
          cp -r node_modules/ dist/layer/nodejs/
      - name: npm-install
        working-directory: ./packages/backend
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install
      - name: npm-run-build
        working-directory: ./packages/backend
        run: npm run-script build
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - id: branch
        shell: bash
        run: echo "##[set-output name=name;]$(echo ${GITHUB_REF#refs/heads/})"
      - uses: marvinpinto/action-inject-ssm-secrets@latest
        with:
          ssm_parameter: /defol/${{ steps.branch.outputs.name }}/base/resources-bucket-name
          env_variable_name: RESOURCE_S3_BUCKET
      - name: upload-openapi
        uses: zdurham/s3-upload-github-action@master
        env:
          S3_BUCKET: ${{ env.RESOURCE_S3_BUCKET }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          FILE: ./packages/backend/openapi.yaml
          S3_KEY: ${{ format('defol-{0}-backend/{1}/openapi.yaml', steps.branch.outputs.name, github.sha) }}
      - name: sam-package
        working-directory: ./packages/backend
        run: |
          sam package \
          --s3-bucket ${{ env.RESOURCE_S3_BUCKET }} \
          --output-template-file packaged.yaml \
          --template-file cloudformation.yaml
      - name: sam-deploy
        working-directory: ./packages/backend
        run: |
          sam deploy --template-file packaged.yaml \
          --no-confirm-changeset --no-fail-on-empty-changeset \
          --stack-name defol-${{ steps.branch.outputs.name }}-backend \
          --s3-bucket ${{ env.RESOURCE_S3_BUCKET }} \
          --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }} \
          --parameter-overrides ResourcesBucket=${{ env.RESOURCE_S3_BUCKET }} Sha=${{ github.sha }} \
          Branch=${{ steps.branch.outputs.name }}

  frontend:
    runs-on: ubuntu-latest
    needs: [ params, publish-root ]
    if: always() && (needs.params.outputs.update-libs == 'true' || needs.params.outputs.frontend == 'true')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
      - name: npm-install
        working-directory: ./packages/frontend
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm install
      - name: npm-run-build
        working-directory: ./packages/frontend
        run: npm run-script build
      - id: branch
        shell: bash
        run: echo "##[set-output name=name;]$(echo ${GITHUB_REF#refs/heads/})"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: marvinpinto/action-inject-ssm-secrets@latest
        with:
          ssm_parameter: /defol/${{ steps.branch.outputs.name }}/frontend/cf-distribution-id
          env_variable_name: CFRONT_DIST_ID
      - uses: marvinpinto/action-inject-ssm-secrets@latest
        with:
          ssm_parameter: /defol/${{ steps.branch.outputs.name }}/frontend/bucket-name
          env_variable_name: S3_BUCKET
      - uses: kersvers/s3-sync-with-cloudfront-invalidation@v1.0.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ env.S3_BUCKET }}
          DISTRIBUTION_ID: ${{ env.CFRONT_DIST_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: ./packages/frontend/build
